name: barber_shop_app
description: A new Flutter project for Barber Shop Booking.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  go_router: ^12.1.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_fonts: ^6.1.0
  intl: ^0.19.0
  table_calendar: ^3.0.9
  uuid: ^4.2.2
  equatable: ^2.0.5
  cupertino_icons: ^1.0.2
  # Graphics and animations
  animate_do: ^3.3.4
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10
  lottie: ^3.1.2
  flutter_staggered_animations: ^1.1.1
  calendar_view: ^1.2.0
  url_launcher: ^6.2.2
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^10.6.0
  image_picker: ^1.2.1
  firebase_storage: ^12.4.10
  firebase_messaging: ^15.2.10
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_premium.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0A0A0A"
  adaptive_icon_foreground: "assets/images/icon_premium.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/gallery/
